"""add_uploaded_files_table

Revision ID: 40cdddf2a8ad
Revises: e299cbcb61e8
Create Date: 2026-06-02 13:17:23.312195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cdddf2a8ad'
down_revision: Union[str, None] = 'e299cbcb61e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
