"""add_ai_suggestion_fields_to_crm

Revision ID: 8f93eb839957
Revises: 40cdddf2a8ad
Create Date: 2026-06-02 18:04:33.133696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f93eb839957'
down_revision: Union[str, None] = '40cdddf2a8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_resource_id'), 'uploaded_files', ['resource_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_resource_type'), 'uploaded_files', ['resource_type'], unique=False)
    op.add_column('opportunities', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('opportunities', sa.Column('validation_status', sa.String(length=20), nullable=False))
    op.add_column('opportunities', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('source_url', sa.String(length=800), nullable=True))
    op.add_column('opportunities', sa.Column('ai_notes', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('validated_by', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_opportunities_validation_status'), 'opportunities', ['validation_status'], unique=False)
    op.add_column('organizations', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('organizations', sa.Column('validation_status', sa.String(length=20), nullable=False))
    op.add_column('organizations', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('organizations', sa.Column('source_url', sa.String(length=800), nullable=True))
    op.add_column('organizations', sa.Column('ai_notes', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('validated_by', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_organizations_source'), 'organizations', ['source'], unique=False)
    op.create_index(op.f('ix_organizations_validation_status'), 'organizations', ['validation_status'], unique=False)
    op.add_column('tenders', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('tenders', sa.Column('validation_status', sa.String(length=20), nullable=False))
    op.add_column('tenders', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('tenders', sa.Column('ai_notes', sa.Text(), nullable=True))
    op.add_column('tenders', sa.Column('validated_by', sa.String(length=255), nullable=True))
    op.add_column('tenders', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tenders_source'), 'tenders', ['source'], unique=False)
    op.create_index(op.f('ix_tenders_validation_status'), 'tenders', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_validation_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source'), table_name='tenders')
    op.drop_column('tenders', 'validated_at')
    op.drop_column('tenders', 'validated_by')
    op.drop_column('tenders', 'ai_notes')
    op.drop_column('tenders', 'confidence_score')
    op.drop_column('tenders', 'validation_status')
    op.drop_column('tenders', 'source')
    op.drop_index(op.f('ix_organizations_validation_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_source'), table_name='organizations')
    op.drop_column('organizations', 'validated_at')
    op.drop_column('organizations', 'validated_by')
    op.drop_column('organizations', 'ai_notes')
    op.drop_column('organizations', 'source_url')
    op.drop_column('organizations', 'confidence_score')
    op.drop_column('organizations', 'validation_status')
    op.drop_column('organizations', 'source')
    op.drop_index(op.f('ix_opportunities_validation_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_column('opportunities', 'validated_at')
    op.drop_column('opportunities', 'validated_by')
    op.drop_column('opportunities', 'ai_notes')
    op.drop_column('opportunities', 'source_url')
    op.drop_column('opportunities', 'confidence_score')
    op.drop_column('opportunities', 'validation_status')
    op.drop_column('opportunities', 'source')
    op.drop_index(op.f('ix_uploaded_files_resource_type'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_resource_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
