"""initial_schema_v1

Revision ID: e299cbcb61e8
Revises: 
Create Date: 2026-06-02 03:19:59.129263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e299cbcb61e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=False),
    sa.Column('seniority', sa.String(length=80), nullable=False),
    sa.Column('languages', sa.String(length=255), nullable=False),
    sa.Column('mission_types', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('tools', sa.Text(), nullable=True),
    sa.Column('governance_rules', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_profiles_domain'), 'agent_profiles', ['domain'], unique=False)
    op.create_index(op.f('ix_agent_profiles_id'), 'agent_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_is_active'), 'agent_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_profiles_name'), 'agent_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_agent_profiles_seniority'), 'agent_profiles', ['seniority'], unique=False)
    op.create_index(op.f('ix_agent_profiles_slug'), 'agent_profiles', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_label', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('organization_type', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_country'), 'organizations', ['country'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_organization_type'), 'organizations', ['organization_type'], unique=False)
    op.create_index(op.f('ix_organizations_sector'), 'organizations', ['sector'], unique=False)
    op.create_table('scheduler_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=120), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_logs_id'), 'scheduler_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_logs_job_id'), 'scheduler_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_scheduler_logs_status'), 'scheduler_logs', ['status'], unique=False)
    op.create_table('sector_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_key', sa.String(length=80), nullable=False),
    sa.Column('sector_label', sa.String(length=120), nullable=False),
    sa.Column('deliverable_type', sa.String(length=80), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_templates_deliverable_type'), 'sector_templates', ['deliverable_type'], unique=False)
    op.create_index(op.f('ix_sector_templates_id'), 'sector_templates', ['id'], unique=False)
    op.create_index(op.f('ix_sector_templates_sector_key'), 'sector_templates', ['sector_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('professional_email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_professional_email'), 'contacts', ['professional_email'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('opportunity_type', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('potential_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.DateTime(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_country'), 'opportunities', ['country'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_opportunities_priority'), 'opportunities', ['priority'], unique=False)
    op.create_index(op.f('ix_opportunities_sector'), 'opportunities', ['sector'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=800), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('go_no_go_score', sa.Integer(), nullable=True),
    sa.Column('go_no_go_decision', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_buyer_name'), 'tenders', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_tenders_go_no_go_decision'), 'tenders', ['go_no_go_decision'], unique=False)
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_opportunity_id'), 'tenders', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_tenders_reference'), 'tenders', ['reference'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_submission_deadline'), 'tenders', ['submission_deadline'], unique=False)
    op.create_index(op.f('ix_tenders_title'), 'tenders', ['title'], unique=False)
    op.create_table('agent_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(length=120), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('expected_deliverable', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('human_reviewer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_assignments_agent_id'), 'agent_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_assignments_assignment_type'), 'agent_assignments', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_agent_assignments_id'), 'agent_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_agent_assignments_opportunity_id'), 'agent_assignments', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_agent_assignments_priority'), 'agent_assignments', ['priority'], unique=False)
    op.create_index(op.f('ix_agent_assignments_status'), 'agent_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_agent_assignments_tender_id'), 'agent_assignments', ['tender_id'], unique=False)
    op.create_table('go_no_go_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_go_no_go_criteria_id'), 'go_no_go_criteria', ['id'], unique=False)
    op.create_index(op.f('ix_go_no_go_criteria_name'), 'go_no_go_criteria', ['name'], unique=False)
    op.create_index(op.f('ix_go_no_go_criteria_recommendation'), 'go_no_go_criteria', ['recommendation'], unique=False)
    op.create_index(op.f('ix_go_no_go_criteria_tender_id'), 'go_no_go_criteria', ['tender_id'], unique=False)
    op.create_table('tender_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('requirement_code', sa.String(length=120), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirement_type', sa.String(length=120), nullable=True),
    sa.Column('response_strategy', sa.Text(), nullable=True),
    sa.Column('proof_or_deliverable', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_requirements_id'), 'tender_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_tender_requirements_requirement_code'), 'tender_requirements', ['requirement_code'], unique=False)
    op.create_index(op.f('ix_tender_requirements_requirement_type'), 'tender_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_tender_requirements_status'), 'tender_requirements', ['status'], unique=False)
    op.create_index(op.f('ix_tender_requirements_tender_id'), 'tender_requirements', ['tender_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['agent_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_action_type'), 'agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_actions_assignment_id'), 'agent_actions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_id'), 'agent_actions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_actions_priority'), 'agent_actions', ['priority'], unique=False)
    op.create_index(op.f('ix_agent_actions_requires_human_approval'), 'agent_actions', ['requires_human_approval'], unique=False)
    op.create_index(op.f('ix_agent_actions_status'), 'agent_actions', ['status'], unique=False)
    op.create_table('compliance_matrix_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('requirement_code', sa.String(length=120), nullable=True),
    sa.Column('requirement_summary', sa.Text(), nullable=False),
    sa.Column('compliance_status', sa.String(length=80), nullable=False),
    sa.Column('response_location', sa.String(length=255), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('gap', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_matrix_items_compliance_status'), 'compliance_matrix_items', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_compliance_matrix_items_id'), 'compliance_matrix_items', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_matrix_items_requirement_code'), 'compliance_matrix_items', ['requirement_code'], unique=False)
    op.create_index(op.f('ix_compliance_matrix_items_requirement_id'), 'compliance_matrix_items', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_compliance_matrix_items_tender_id'), 'compliance_matrix_items', ['tender_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('deliverable_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('audience', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignment_id'], ['agent_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_action_id'), 'deliverables', ['action_id'], unique=False)
    op.create_index(op.f('ix_deliverables_assignment_id'), 'deliverables', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_deliverables_deliverable_type'), 'deliverables', ['deliverable_type'], unique=False)
    op.create_index(op.f('ix_deliverables_id'), 'deliverables', ['id'], unique=False)
    op.create_index(op.f('ix_deliverables_opportunity_id'), 'deliverables', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_deliverables_status'), 'deliverables', ['status'], unique=False)
    op.create_index(op.f('ix_deliverables_tender_id'), 'deliverables', ['tender_id'], unique=False)
    op.create_index(op.f('ix_deliverables_title'), 'deliverables', ['title'], unique=False)
    op.create_table('deliverable_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section_key', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('owner_agent_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agent_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverable_sections_deliverable_id'), 'deliverable_sections', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_deliverable_sections_id'), 'deliverable_sections', ['id'], unique=False)
    op.create_index(op.f('ix_deliverable_sections_owner_agent_id'), 'deliverable_sections', ['owner_agent_id'], unique=False)
    op.create_index(op.f('ix_deliverable_sections_section_key'), 'deliverable_sections', ['section_key'], unique=False)
    op.create_index(op.f('ix_deliverable_sections_status'), 'deliverable_sections', ['status'], unique=False)
    op.create_index(op.f('ix_deliverable_sections_title'), 'deliverable_sections', ['title'], unique=False)
    op.create_table('deliverable_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverable_versions_deliverable_id'), 'deliverable_versions', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_deliverable_versions_id'), 'deliverable_versions', ['id'], unique=False)
    op.create_index(op.f('ix_deliverable_versions_version'), 'deliverable_versions', ['version'], unique=False)
    op.create_table('agent_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('contribution_type', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['deliverable_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_contributions_action_id'), 'agent_contributions', ['action_id'], unique=False)
    op.create_index(op.f('ix_agent_contributions_agent_id'), 'agent_contributions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_contributions_contribution_type'), 'agent_contributions', ['contribution_type'], unique=False)
    op.create_index(op.f('ix_agent_contributions_deliverable_id'), 'agent_contributions', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_agent_contributions_id'), 'agent_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_contributions_section_id'), 'agent_contributions', ['section_id'], unique=False)
    op.create_index(op.f('ix_agent_contributions_status'), 'agent_contributions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_contributions_status'), table_name='agent_contributions')
    op.drop_index(op.f('ix_agent_contributions_section_id'), table_name='agent_contributions')
    op.drop_index(op.f('ix_agent_contributions_id'), table_name='agent_contributions')
    op.drop_index(op.f('ix_agent_contributions_deliverable_id'), table_name='agent_contributions')
    op.drop_index(op.f('ix_agent_contributions_contribution_type'), table_name='agent_contributions')
    op.drop_index(op.f('ix_agent_contributions_agent_id'), table_name='agent_contributions')
    op.drop_index(op.f('ix_agent_contributions_action_id'), table_name='agent_contributions')
    op.drop_table('agent_contributions')
    op.drop_index(op.f('ix_deliverable_versions_version'), table_name='deliverable_versions')
    op.drop_index(op.f('ix_deliverable_versions_id'), table_name='deliverable_versions')
    op.drop_index(op.f('ix_deliverable_versions_deliverable_id'), table_name='deliverable_versions')
    op.drop_table('deliverable_versions')
    op.drop_index(op.f('ix_deliverable_sections_title'), table_name='deliverable_sections')
    op.drop_index(op.f('ix_deliverable_sections_status'), table_name='deliverable_sections')
    op.drop_index(op.f('ix_deliverable_sections_section_key'), table_name='deliverable_sections')
    op.drop_index(op.f('ix_deliverable_sections_owner_agent_id'), table_name='deliverable_sections')
    op.drop_index(op.f('ix_deliverable_sections_id'), table_name='deliverable_sections')
    op.drop_index(op.f('ix_deliverable_sections_deliverable_id'), table_name='deliverable_sections')
    op.drop_table('deliverable_sections')
    op.drop_index(op.f('ix_deliverables_title'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_tender_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_status'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_opportunity_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_deliverable_type'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_assignment_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_action_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_compliance_matrix_items_tender_id'), table_name='compliance_matrix_items')
    op.drop_index(op.f('ix_compliance_matrix_items_requirement_id'), table_name='compliance_matrix_items')
    op.drop_index(op.f('ix_compliance_matrix_items_requirement_code'), table_name='compliance_matrix_items')
    op.drop_index(op.f('ix_compliance_matrix_items_id'), table_name='compliance_matrix_items')
    op.drop_index(op.f('ix_compliance_matrix_items_compliance_status'), table_name='compliance_matrix_items')
    op.drop_table('compliance_matrix_items')
    op.drop_index(op.f('ix_agent_actions_status'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_requires_human_approval'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_priority'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_assignment_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_action_type'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_tender_requirements_tender_id'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_status'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_requirement_type'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_requirement_code'), table_name='tender_requirements')
    op.drop_index(op.f('ix_tender_requirements_id'), table_name='tender_requirements')
    op.drop_table('tender_requirements')
    op.drop_index(op.f('ix_go_no_go_criteria_tender_id'), table_name='go_no_go_criteria')
    op.drop_index(op.f('ix_go_no_go_criteria_recommendation'), table_name='go_no_go_criteria')
    op.drop_index(op.f('ix_go_no_go_criteria_name'), table_name='go_no_go_criteria')
    op.drop_index(op.f('ix_go_no_go_criteria_id'), table_name='go_no_go_criteria')
    op.drop_table('go_no_go_criteria')
    op.drop_index(op.f('ix_agent_assignments_tender_id'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_status'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_priority'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_opportunity_id'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_id'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_assignment_type'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_agent_id'), table_name='agent_assignments')
    op.drop_table('agent_assignments')
    op.drop_index(op.f('ix_tenders_title'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_submission_deadline'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_reference'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_opportunity_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_go_no_go_decision'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_buyer_name'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_sector'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_priority'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_country'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_contacts_professional_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sector_templates_sector_key'), table_name='sector_templates')
    op.drop_index(op.f('ix_sector_templates_id'), table_name='sector_templates')
    op.drop_index(op.f('ix_sector_templates_deliverable_type'), table_name='sector_templates')
    op.drop_table('sector_templates')
    op.drop_index(op.f('ix_scheduler_logs_status'), table_name='scheduler_logs')
    op.drop_index(op.f('ix_scheduler_logs_job_id'), table_name='scheduler_logs')
    op.drop_index(op.f('ix_scheduler_logs_id'), table_name='scheduler_logs')
    op.drop_table('scheduler_logs')
    op.drop_index(op.f('ix_organizations_sector'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_organization_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_country'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_profiles_slug'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_seniority'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_name'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_is_active'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_domain'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
